services:
  audiobookshelf:
    image: ghcr.io/boondawgy/audiobookshelf:custom
    pull_policy: always
    container_name: audiobookshelf
    labels:
      com.centurylinklabs.watchtower.enable: "true"

    ports:
      - "13378:80"

    volumes:
      - /mnt/@usb/sda2/Audiobooks:/audiobooks
      - /mnt/@usb/sda2/Podcasts:/podcasts
      - /mnt/@usb/sda2/Books:/books
      - /volume1/appdata/audiobookshelf/metadata:/metadata
      - /volume1/appdata/audiobookshelf/config:/config

    networks:
      - media_services

    restart: unless-stopped

networks:
  media_services:
    name: media_services
    external: true
